apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app
          image: yourdockerhubusername/banking-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017

apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  selector:
    app: banking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
