# Stage 1: Build
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# ใช้ build tags จาก docker-compose
ARG BUILD_TAGS
RUN go build -tags "${BUILD_TAGS}" -o los-service ./cmd/los-service

# Stage 2: Runtime
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/los-service .

ENV PORT=8080
EXPOSE ${PORT}

CMD ["./los-service"]
