# syntax=docker/dockerfile:1

FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o los-service ./cmd/los-service

FROM alpine:3.18
WORKDIR /root/
COPY --from=builder /app/los-service .
EXPOSE 8080
CMD ["./los-service"]
