name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-tets:
    name: Build and Unit Test 
    runs-on: ubuntu-latest 

    services:
      mysql:
        image:  mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root 
          MYSQL_DATABASE: safebank
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
   
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Wait for MySQL to be healthy 
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Download dependencies
        run: go mod tidy 

      - name: Run unit tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: safebank
        run: go test ./... 

      - name: Build Docker image 
        run: docker build -t safebank .  




