version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:8081"
    env_file:
      - .env
    # restart: unless-stopped

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "${BOOKING_SERVICE_PORT}:8082"
    env_file:
      - .env
    # restart: unless-stopped

