# user-service:
#   server:
#     port: ${USER_SERVICE_PORT}

#   sqlserver:
#     user: ${USER_SQLSERVER_USER}
#     password: ${USER_SQLSERVER_PASSWORD}
#     host: ${USER_SQLSERVER_HOST}
#     port: ${USER_SQLSERVER_PORT}
#     dbname: ${USER_SQLSERVER_DB}

# booking-service:
#   server:
#     port: ${BOOKING_SERVICE_PORT}

#   sqlserver:
#     user: ${BOOKING_SQLSERVER_USER}
#     password: ${BOOKING_SQLSERVER_PASSWORD}
#     host: ${BOOKING_SQLSERVER_HOST}
#     port: ${BOOKING_SQLSERVER_PORT}
#     dbname: ${BOOKING_SQLSERVER_DB}

# jwt:
#   secret: ${JWT_SECRET}
