name: CI 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  

jobs:
  build:
    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v3

    - names: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.1

    - name: Build 
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image 
      run: docker build -t  bank/banking-app:latest .

    - name: Push Docker image 
      uses: docker/login-action@v2 

    - name: Push image
      run: docker push bank/banking-app:latest

