name: Auth Service CI/CD

on:
  push:
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-service.yml"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Setup Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"

    # 3. Build Binary
    - name: Build Go App
      working-directory: ./auth-service
      run: go build -o auth-service ./cmd/server

    # 4. Login Docker Registry
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build & Push Docker Image
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./auth-service
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }}

    # 6. Setup kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 7. Connect Kubernetes Cluster
    - name: Set kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    # 8. Deployment Rolling Update
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/auth-service \
        auth-service=${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }}
