name: Auth Service CI/CD (Local Docker)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --prefix ./auth-service

      - name: Run tests
        run: npm test --prefix ./auth-service

      - name: Build Docker image
        run: docker build -t auth-service:latest ./auth-service

      - name: Run container
        run: |
          docker stop auth-service || true
          docker rm auth-service || true
          docker run -d --name auth-service -p 8081:8081 auth-service:latest
