apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: contract-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
      - name: notification-worker
        image: artis50217/notification-worker:latest
