version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:8081"
    env_file:
      - .env
    networks:
      - app-network

  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "${STOCK_SERVICE_PORT}:8082"
    env_file:
      - .env
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "${ORDER_SERVICE_PORT}:8083"
    env_file:
      - .env
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    
