version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:8081"
    env_file:
      - .env

  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "${STOCK_SERVICE_PORT}:8082"
    env_file:
      - .env    

